version: "3.8"

services:
    db: 
        image: mysql:8
        container_name: istamo2020
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: tamo
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - '3306:3306'
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        depends_on:
          - db
        ports:
          - 8081:80
        environment:
            PMA_HOST: istamo2020
            PMA_PORT: 3306
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: tamo
        restart: always